config/routes.rb
Rails.application.routes.draw do
  # 管理者機能
  namespace :admin do
    resources :users, except: %i[new create]
  end

  # 予想機能
  resources :pro_games, only: [:create] do
    resources :pro_game_predicts, only: %i[new create]
    resources :pro_game_predict_comments, only: %i[create destroy]
  end

  # 予想閲覧機能
  resources :game_predicts, only: [:show]

  # actioncable
  mount ActionCable.server => '/cable'
  # メール関係
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  resources :password_resets, only: %i[new create edit update]

  # チャットルーム
  resources :chatrooms, only: :show do
    resources :chats, only: %i[index create destroy]
  end

  # ログイン
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => 'user_sessions#create'
  post 'logout' => 'user_sessions#destroy', :as => :logout
  # ゲストログイン機能
  post 'guest_login', to: 'user_sessions#guest_login'

  # ユーザー
  resources :users, except: [:index]

  # 利用規約・プライバシーポリシーなど
  get 'static_pages/terms_of_service' => 'static_pages#terms_of_service'
  get 'static_pages/privacy_policy' => 'static_pages#privacy_policy'

  # トップ
  get 'static_pages/top'
  root 'static_pages#top'
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :profile, ProfileUploader

  has_many :chats, dependent: :destroy
  has_many :pro_game_predicts, dependent: :destroy
  has_many :pro_game_predict_comments, dependent: :destroy

  validates :nickname, presence: true, length: { maximum: 16 }, invalid_words: true
  validates :password, length: { minimum: 8, maximum: 20 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :reset_password_token, uniqueness: true, allow_nil: true
  validates :role, presence: true

  enum role: { general: 0, guest: 1, admin: 2 }
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :reject_not_admin_user
    before_action :set_user, only: %i[show edit update destroy]

    def index
      @users = User.all
    end

    def show; end

    def edit; end

    def update
      if @user.update(user_params)
        redirect_to admin_users_path, success: 'ユーザーを更新しました。'
      else
        flash.now[:danger] = 'ユーザー更新に失敗しました。'
        render 'admin/users/edit'
      end
    end

    def destroy
      @user.destroy
      redirect_to admin_users_path, success: 'ユーザーを削除しました。'
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:profile_cache, :nickname, :email)
    end

    def reject_not_admin_user
      redirect_to root_path, success: '権限がありません。' unless current_user.role_before_type_cast == 2
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: %i[index show edit update destroy]
  before_action :set_user, only: %i[show edit update destroy]
  before_action :correct_user, only: %i[edit update destroy]
  before_action :logout_guest_user, only: :new
  before_action :rejct_guest_user, only: %i[edit update]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user_predicts = @user.pro_game_predicts.where(created_at: Time.current.ago(2.days).beginning_of_day..Time.current)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      redirect_to user_url(@user), success: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to user_url(@user), success: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to root_path, success: t('.danger')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:profile, :profile_cache, :nickname, :email, :password, :password_confirmation)
  end

  def correct_user
    redirect_back fallback_location: chatroom_path(Date.today), danger: I18n.t('users.correct_user.danger') if @user != current_user
  end

  def rejct_guest_user
    redirect_back fallback_location: chatroom_path(Date.today), danger: t('users.reject_guest_user.danger') if current_user.guest?
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <%= render 'shared/error_message', object: user %>

  <%= image_tag user.profile.url, id: 'profile_preview', class: 'rounded-circle mb-3 profile-image d-block mx-auto', style: 'width:150px; height:150px; border-radius:50%; object-fit: cover;' %>
  <div class="field">
    <%= form.label :profile, class: 'form-label' %>
    <%= form.file_field :profile, id: 'profile', class: 'form-control' %>
    <%= form.hidden_field :profile_cache %>
  </div>

  <div class="field">
    <%= form.label :nickname, class: 'form-label' %>
    <%= form.text_field :nickname, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :email, class: 'form-label' %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <% if current_user && !current_user.guest? %>
    <%= link_to "アカウントを削除", user_path, method: :delete, data: { confirm: "アカウントを本当に削除しますか？" }, class: 'text-danger' %>
  <% end %>

  <% unless current_user %>
  <div class="field">
    <%= form.label :password, class: 'form-label' %><br />
    <%= form.password_field :password, class: 'form-control' %>
  </div>
  
  <div class="field">
    <%= form.label :password_confirmation, class: 'form-label' %><br />
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <% end %>

  <div class="actions my-3">
    <%= form.submit class: 'btn btn-primary d-block mx-auto' %>
  </div>

<% end %>

app/views/users/_pro_game_predict_result.html.erb
<% binding.pry%>
<div class="one-game-predict-result row border border-info rounded p-2 mb-3 ">
        <div class="row">
          <h4 class="col fw-bold"><%= @user_predict.pro_game.first_base_side_pro_team %></h4>
          <div class="col">
            <%= yesterday_pro_game_predict.pro_game.first_base_side_score %>-<%= yesterday_pro_game_predict.pro_game.third_base_side_score %><p class ="col">あなたの予想:<%= yesterday_pro_game_predict.first_base_side_score %>-<%= yesterday_pro_game_predict.third_base_side_score %></p>
          </div>
          <h4 class="col fw-bold"><%= yesterday_pro_game_predict.pro_game.third_base_side_pro_team %></h4>
          <div class="col">
            <div class="text-info">
              <% if yesterday_pro_game_predict.point == 100 %>
                <i class="far fa-bolt" style='color: #FFD700; width: 40px; height: 40px;'></i>
                <%# <i class="fa-solid fa-bolt" style='width: 40px; height: 40px'></i> %>
              <% elsif 100 > yesterday_pro_game_predict.point && yesterday_pro_game_predict.point >= 61 %>
                <i class="far fa-star" style='color: #FFD700; width: 40px; height: 40px;'></i>
                <%# <i class="fa-solid fa-face-grin-stars" style='width: 40px; height: 40px'></i> %>
              <% elsif 61 > yesterday_pro_game_predict.point && yesterday_pro_game_predict.point >= 41 %>
                <i class="far fa-frown" style='color: #FFD700; width: 40px; height: 40px;'></i>
                <%# <i class="fa-solid fa-face-frown" style='width: #FFD700; 40px; height: 40px'></i> %>
              <% elsif 41 > yesterday_pro_game_predict.point && yesterday_pro_game_predict.point >= 11 %>
                <i class="far fa-grin-beam-sweat"  style='width: 40px; height: 40px;'></i>
                <%# <i class="fa-solid fa-face-grin-beam-sweat" style='color: #FFD700; width: 40px; height: 40px'></i> %>
              <% else %>
                <i class="fas fa-poop" style='width: 40px; height: 40px;'></i>
                <%# <i class="fa-solid fa-poo" style='width: #FFD700; 40px; height: 40px'></i> %>
              <% end %>
            </div>
            <div class="fw-bold"><%= yesterday_pro_game_predict.point %>pt</div>
          </div>
        </div>
      </div>

app/views/users/edit.html.erb
<% breadcrumb :edit_user, @user %>
<div class="container">
<h1 class="pt-5">ユーザー編集</h1>
<%= render 'form', user: @user %>

</div>

app/views/users/new.html.erb
<div class="container">
  <h1 class="my-3 text-center"><%= t".title" %></h1>
  <%= render 'form', user: @user %>
  <div>
    <%= link_to "ログインはこちら", login_path %>
  </div>
</div>

app/views/users/show.html.erb
<% breadcrumb :user, @user %>
<p id="notice"><%= notice %></p>
<div class="container text-center">

  <div class="pt-4">
    <p><%= image_tag @user.profile.url,class: 'border border-2', style: 'height:100px; width:100px; border-radius:50%; object-fit: cover;' %></p>
  </div>

  <h5 class="fw-bold">
    <%= @user.nickname %>
  </h5>
  <% if @user == current_user %>
    <%= link_to edit_user_path(@user), class: "btn btn-outline-primary edit-link-#{@user.id}" do %>
      <%= t(".edit") %> <i class="fas fa-edit"></i>
    <% end %>
  <% end %>

  <h4 class="fw-bold my-4"><%= @user.nickname %> の過去３日の予想成績</h4>
    <% if current_user.guest? && @user == current_user %>
    <p class="text-danger">ゲストユーザーは予想成績が記録されません。</p>
    <% else %>
      <% @user_predicts.each do |user_predict| %>
        <%= link_to new_pro_game_pro_game_predict_path(user_predict.pro_game),  class:"text-dark text-decoration-none one-game-predict-result border row rounded p-2 mb-3" do %>
          <div>
            <div class="row">
              <h4 class="col fw-bold"><%= user_predict.pro_game.first_base_side_pro_team %></h4>
              <h4 class="col fw-bold"><%= user_predict.pro_game.first_base_side_score %>-<%= user_predict.pro_game.third_base_side_score %></h4>
              <h4 class="col fw-bold"><%= user_predict.pro_game.third_base_side_pro_team %></h4>
            </div>
            <div class="text-center">
              <%= @user.nickname %>の予想:<span class="fw-bold  text-primary"><%= user_predict.first_base_side_score %>-<%= user_predict.third_base_side_score %></span>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>

</div>