config/routes.rb
Rails.application.routes.draw do
  # 管理者機能
  namespace :admin do
    resources :users, except: %i[new create]
  end

  # 予想機能
  resources :pro_games, only: [:create] do
    resources :pro_game_predicts, only: %i[new create]
    resources :pro_game_predict_comments, only: %i[create destroy]
  end

  # 予想閲覧機能
  resources :game_predicts, only: [:show]

  # actioncable
  mount ActionCable.server => '/cable'
  # メール関係
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  resources :password_resets, only: %i[new create edit update]

  # チャットルーム
  resources :chatrooms, only: :show do
    resources :chats, only: %i[index create destroy]
  end

  # ログイン
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => 'user_sessions#create'
  post 'logout' => 'user_sessions#destroy', :as => :logout
  # ゲストログイン機能
  post 'guest_login', to: 'user_sessions#guest_login'

  # ユーザー
  resources :users, except: [:index]

  # 利用規約・プライバシーポリシーなど
  get 'static_pages/terms_of_service' => 'static_pages#terms_of_service'
  get 'static_pages/privacy_policy' => 'static_pages#privacy_policy'

  # トップ
  get 'static_pages/top'
  root 'static_pages#top'
end

app/views/shared/_error_message.html.erb
<% if object.errors.present? %>
  <% object.errors.full_messages.each do |message| %>
    <li>
      <%= message %>
    </li>
  <% end %>
<% end%>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% if params[:controller] == "chats" && params[:action] == "index" %>
  <div class="pe-auto position-fixed" style="margin-top:57px; left:0px; right:0px; z-index: 1020;">
    <div class="alert alert-<%= message_type %> alert-dismissible mb-0"><%= message %><button type="button" class="btn-close pe-0" data-bs-dismiss="alert" aria-label="Close"></button></div>
  </div>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible mb-0"><%= message %><button type="button" class="btn-close pe-0" data-bs-dismiss="alert" aria-label="Close"></button></div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer p-5 text-center bg-dark text-light" style="backgroud-color: #ADD8E6;">
<p>©︎2022 野球バカ実況</p>
 
  <%= link_to "利用規約", static_pages_terms_of_service_path, class: 'px-2' %>
  <%= link_to "プライバシーポリシー", static_pages_privacy_policy_path, class: 'px-2'  %>
  <%= link_to "問い合わせ", "https://twitter.com/baseballapp514", target: :_blank, rel: "noopener noreferrer", class: 'px-2'  %>
</footer>

app/views/shared/_header.html.erb
<div class="header">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top application-header">
  <div class="container-fluid">
    <div class="fw-bold"><%= link_to '野球バカ実況', root_path, class:'navbar-brand' %></div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

      <% unless current_user %>
        <li class="nav-item">
          <%= link_to 'ゲストログイン', guest_login_path, method: :post, class: 'nav-link', aria_current: 'page' %>
        </li>
        <li class="nav-item">
          <%= link_to '会員登録', new_user_path, class: 'nav-link', aria_current: 'page' %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログイン', login_path, class: 'nav-link', aria_current: 'page' %>
        </li>
      <% else %>
        <% if current_user.guest? %>
          <li class="nav-item">
          <%= link_to '会員登録', new_user_path, class: 'nav-link', aria_current: 'page' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログイン', login_path, class: 'nav-link', aria_current: 'page' %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'リアルタイム実況', chatroom_path(Date.today), class: 'nav-link', aria_current: 'page' %>
        </li>
        <li class="nav-item">
          <%= link_to '今日の試合予想', game_predict_path(Date.today), class: 'nav-link' %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="pe-1">プロフィール</span><i class="fas fa-user"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="navbarDarkDropdownMenuLink">
            <li><%= link_to 'プロフィール', user_path(current_user), class: 'nav-link' %></li>
            <li><%= link_to 'プロフィール編集', edit_user_path(current_user), class: 'nav-link' %></li>
            <li><%= link_to 'ログアウト', logout_path, method: :post, class: 'nav-link' %></li>
          </ul>
        </li>
      <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="pe-1">その他</span><i class="fas fa-cog"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="navbarDarkDropdownMenuLink">
            <li><%= link_to 'プライバシーポリシー', static_pages_privacy_policy_path, class: 'nav-link' %></li>
            <li><%= link_to '利用規約', static_pages_terms_of_service_path, class: 'nav-link' %></li>
            <li><%= link_to '問い合わせ', "https://twitter.com/baseballapp514", target: :_blank, rel: "noopener noreferrer", class: 'nav-link' %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
</div>