config/routes.rb
Rails.application.routes.draw do
  # 管理者機能
  namespace :admin do
    resources :users, except: %i[new create]
  end

  # 予想機能
  resources :pro_games, only: [:create] do
    resources :pro_game_predicts, only: %i[new create]
    resources :pro_game_predict_comments, only: %i[create destroy]
  end

  # 予想閲覧機能
  resources :game_predicts, only: [:show]

  # actioncable
  mount ActionCable.server => '/cable'
  # メール関係
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  resources :password_resets, only: %i[new create edit update]

  # チャットルーム
  resources :chatrooms, only: :show do
    resources :chats, only: %i[index create destroy]
  end

  # ログイン
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => 'user_sessions#create'
  post 'logout' => 'user_sessions#destroy', :as => :logout
  # ゲストログイン機能
  post 'guest_login', to: 'user_sessions#guest_login'

  # ユーザー
  resources :users, except: [:index]

  # 利用規約・プライバシーポリシーなど
  get 'static_pages/terms_of_service' => 'static_pages#terms_of_service'
  get 'static_pages/privacy_policy' => 'static_pages#privacy_policy'

  # トップ
  get 'static_pages/top'
  root 'static_pages#top'
end

app/models/pro_game_predict.rb
class ProGamePredict < ApplicationRecord
  belongs_to :user
  belongs_to :pro_game
  has_many :pro_game_predict_comments

  enum win_or_lose: { first_base_side_win: 0, third_base_side_win: 1, draw: 2 }

  validates :first_base_side_score, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 33 }, format: { with: /\A[0-9]+\z/ }
  validates :third_base_side_score, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 33 }, format: { with: /\A[0-9]+\z/ }
  validates :user_id, presence: true
  validates :pro_game_id, presence: true
  validates :win_or_lose, presence: true
  validates :point, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }, allow_nil: true

  # 予想の勝敗を判定する
  def input_win_or_lose
    if first_base_side_score > third_base_side_score
      self.win_or_lose = :first_base_side_win
    elsif first_base_side_score < third_base_side_score
      self.win_or_lose = :third_base_side_win
    elsif first_base_side_score == third_base_side_score
      self.win_or_lose = :draw
    end
  end
end

app/controllers/pro_game_predicts_controller.rb
class ProGamePredictsController < ApplicationController
  before_action :require_login
  before_action :set_today_pro_game, only: %i[new create]
  before_action :time_check, only: :create

  def new
    @pro_game_predict_comments = @today_pro_game.pro_game_predict_comments.order(created_at: :desc).includes(:user, :pro_game, :pro_game_predict)
    @current_user_predict = current_user.pro_game_predicts.find_by(pro_game_id: params[:pro_game_id]) if current_user
  end

  def create
    @pro_game_predict = current_user.pro_game_predicts.new(predict_params)
    @pro_game_predict.input_win_or_lose
    if @pro_game_predict.save
      redirect_to request.referer, success: t('.success')
    else
      redirect_to request.referer, danger: t('.danger')
    end
  end

  def edit; end

  def update; end

  private

  def predict_params
    params.permit(:first_base_side_score, :third_base_side_score, :pro_game_id)
  end

  def set_today_pro_game
    @today_pro_game = ProGame.find(params[:pro_game_id])
  end

  def time_check
    redirect_to request.referer, danger: '試合開始予定時間を過ぎているため投稿できません' if @today_pro_game.start_at < Time.current
  end
end

app/views/pro_game_predicts/_already_predict.html.erb
<div class="row one-game m-3 fw-bold border border-2">
  <div class="col-3 mt-3">
    <h4 class="fw-bold mt-3"><%= today_pro_game.first_base_side_pro_team %></h4>
    <%= today_pro_game.first_base_side_pitcher %>
  </div>
  <div class="col-2 mt-3">
    <p class="mt-3 mb-1">あなたの予想</p>
    <h5 class="mx-auto fw-bold text-primary"><%= current_user_predict.first_base_side_score %></h5>
  </div>
  <div class="col-2 pt-4 mt-4">
    <%= l today_pro_game.start_at %>
  </div>
  <div class="col-2 mt-3">
    <p class="mt-3 mb-1">あなたの予想</p>
    <h5 class="mx-auto fw-bold text-primary"><%= current_user_predict.third_base_side_score %></h5>
  </div>
  <div class="col-3 mt-3">
    <h4 class="fw-bold mt-3"><%= today_pro_game.third_base_side_pro_team %></h4>
    <%= today_pro_game.third_base_side_pitcher %>
  </div>
  <div>
    投票済み
  </div>
</div>

app/views/pro_game_predicts/_pro_game_predict_comment.erb
<div class="d-flex mb-3">
  
  <%= link_to user_path(pro_game_predict_comment.user), target: :_blank, rel: "noopener noreferrer" do %>
    <div>
      <%= image_tag pro_game_predict_comment.user.profile.url, style: 'width:50px; height:50px; border-radius:50%; object-fit: cover;' %>
    </div>
  <% end %>
    

  <div>
    <div class="ps-1 fw-bold d-inline">
      <%= pro_game_predict_comment.user.nickname %>
    </div>
    <span class="ms-2 p-1 text-light d-inline rounded" style="font-size:90%; margin-right:20px; background-color: #808080;">
      予想:
      <%= today_pro_game.first_base_side_pro_team %>
      <%= pro_game_predict_comment.pro_game_predict.first_base_side_score %>-<%= pro_game_predict_comment.pro_game_predict.third_base_side_score %>
      <%= today_pro_game.third_base_side_pro_team %>
    </span>
    
    <div class="px-3 py-2">
      <%= pro_game_predict_comment.body %>
    </div>
  </div>
</div>

app/views/pro_game_predicts/_today_pro_game.html.erb
<%= form_with model: @pro_game_predict, url: pro_game_pro_game_predicts_url, class: 'border-3' do |f| %>
<div class="row one-game m-3 border border-2">
  <div class="col-3 mt-3">
    <h4 class="fw-bold mt-3"><%= today_pro_game.first_base_side_pro_team %></h4>
    <%= today_pro_game.first_base_side_pitcher %>
  </div>
  <div class="col-2 mt-3">
    <%= f.label :スコア予想, class: 'form-label' %>
    <%= f.number_field :first_base_side_score, name: 'first_base_side_score', id: 'first_base_side_score', min: 0, max: 33, style: 'width:50px;', class: 'form-control mx-auto', type:'tel' %>
  </div>
  <div class="col-2 pt-4 mt-4">
    <%= l today_pro_game.start_at %>
  </div>
  <div class="col-2 mt-3">
    <%= f.label :スコア予想, class: 'form-label' %>
    <%= f.number_field :third_base_side_score, name: 'third_base_side_score', id: 'third_base_side_score', min: 0, max: 33, style: 'width:50px;', class: 'form-control mx-auto', type:'tel' %>
  </div>
  <div class="col-3 mt-3">
    <h4 class="fw-bold mt-3"><%= today_pro_game.third_base_side_pro_team %></h4>
    <%= today_pro_game.third_base_side_pitcher %>
  </div>
  <div>
    <%= f.submit "投票する", class: 'btn btn-primary mb-3', :onclick => "return check_form()" %>
  </div>
</div>
<% end %>
<script>
  function check_form() {
    var first_base_side_pro_team = '<%= today_pro_game.first_base_side_pro_team %>';
    var third_base_side_pro_team = '<%= today_pro_game.third_base_side_pro_team %>';
    var first_base_side_score = document.getElementById('first_base_side_score').value;
    var third_base_side_score = document.getElementById('third_base_side_score').value;

    if ( !first_base_side_score || !third_base_side_score ) {
      window.alert('両チームのスコアを入力してください');
      return false;
    }else if (first_base_side_score.match(/^[^\x01-\x7E\uFF61-\uFF9F]+$/) || third_base_side_score.match(/^[^\x01-\x7E\uFF61-\uFF9F]+$/)) {
      window.alert('半角数字で入力してください');
      return false;
    }
    else {
      var submitMessage = window.confirm(first_base_side_pro_team + ' ' + first_base_side_score + '-' + third_base_side_score + ' ' + third_base_side_pro_team + 'で投票してもいいですか？');
      if (!submitMessage) {
        return false;
      };
    };
  };
</script>

app/views/pro_game_predicts/new.html.erb
<% breadcrumb :pro_game_predict, @today_pro_game %>
<div class="container">
  <section class="text-center">
    <h2 class="pt-5">勝敗予想</h2>
    <% if @current_user_predict %>
      <%= render 'already_predict', { today_pro_game: @today_pro_game, current_user_predict: @current_user_predict } %>
    <% else %>
      <%= render 'today_pro_game', today_pro_game: @today_pro_game %>
    <% end %>
  </section>

  <section>
    <h4 class='mt-5'>予想コメント</h4>
    <p>(140文字以内)</p>
      <%= form_with model: @pro_game_predict_comment, url: pro_game_pro_game_predict_comments_url, local: false, class:'my-3', id: "pro_game_predict_comment_form_#{@today_pro_game.id}" do |f| %>
          <%= f.text_area :body, id:'pro_game_predict_comment_value', class: 'form-control'%>
          <%= f.submit "送信する", class: 'btn btn-outline-primary my-3' %>
      <% end %>
      <div class="pro_game_predict_comments" id="pro_game_predict_comments">
        <%= render partial: 'pro_game_predicts/pro_game_predict_comment', locals: { today_pro_game: @today_pro_game } , collection: @pro_game_predict_comments %>
      </div>
  </section>
</div>